spring:
  profiles:
    active: dev
  datasource:
    driverClassName: org.postgresql.Driver
    sqlScriptEncoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
server:
  error:
    include-message: always
